// ===== DATA STORE (localStorage) =====
const DB = {
  getMembers()      { return JSON.parse(localStorage.getItem('loyalbrew_members') || '[]'); },
  saveMembers(m)    { localStorage.setItem('loyalbrew_members', JSON.stringify(m)); },
  getTxns()         { return JSON.parse(localStorage.getItem('loyalbrew_txns') || '[]'); },
  saveTxns(t)       { localStorage.setItem('loyalbrew_txns', JSON.stringify(t)); },
  getOrders()       { return JSON.parse(localStorage.getItem('loyalbrew_orders') || '[]'); },
  saveOrders(o)     { localStorage.setItem('loyalbrew_orders', JSON.stringify(o)); },
  getMenu()         { return JSON.parse(localStorage.getItem('loyalbrew_menu') || 'null'); },
  saveMenu(m)       { localStorage.setItem('loyalbrew_menu', JSON.stringify(m)); },
  getNewItems()       { return JSON.parse(localStorage.getItem('loyalbrew_new_items') || '[]'); },
  saveNewItems(n)     { localStorage.setItem('loyalbrew_new_items', JSON.stringify(n)); },
  getAnnounceSeen()   { return localStorage.getItem('loyalbrew_announce_seen') || ''; },
  setAnnounceSeen(v)  { localStorage.setItem('loyalbrew_announce_seen', v); },
  getStampCards()     { return JSON.parse(localStorage.getItem('loyalbrew_stamp_cards') || '[]'); },
  saveStampCards(s)   { localStorage.setItem('loyalbrew_stamp_cards', JSON.stringify(s)); },
  getMemberStamps()   { return JSON.parse(localStorage.getItem('loyalbrew_member_stamps') || '{}'); },
  saveMemberStamps(s) { localStorage.setItem('loyalbrew_member_stamps', JSON.stringify(s)); },
  getWallets()        { return JSON.parse(localStorage.getItem('loyalbrew_wallets') || '{}'); },
  saveWallets(w)      { localStorage.setItem('loyalbrew_wallets', JSON.stringify(w)); },
  getWalletTxns()     { return JSON.parse(localStorage.getItem('loyalbrew_wallet_txns') || '[]'); },
  saveWalletTxns(t)   { localStorage.setItem('loyalbrew_wallet_txns', JSON.stringify(t)); },
  getComplaints()        { return JSON.parse(localStorage.getItem('loyalbrew_complaints') || '[]'); },
  saveComplaints(c)      { localStorage.setItem('loyalbrew_complaints', JSON.stringify(c)); },
  getTopupRequests()       { return JSON.parse(localStorage.getItem('loyalbrew_topup_requests') || '[]'); },
  saveTopupRequests(r)     { localStorage.setItem('loyalbrew_topup_requests', JSON.stringify(r)); },
  getCommissions()         { return JSON.parse(localStorage.getItem('loyalbrew_commissions') || '[]'); },
  saveCommissions(c)       { localStorage.setItem('loyalbrew_commissions', JSON.stringify(c)); },
  getPaymentProofs()       { return JSON.parse(localStorage.getItem('loyalbrew_payment_proofs') || '[]'); },
  savePaymentProofs(p)     { localStorage.setItem('loyalbrew_payment_proofs', JSON.stringify(p)); },
  getCurrentMemberPhone()  { return localStorage.getItem('loyalbrew_current_member') || null; },
  setCurrentMemberPhone(p) { if (p) localStorage.setItem('loyalbrew_current_member', p); else localStorage.removeItem('loyalbrew_current_member'); },
};

// ===== MULTI-LANGUAGE SYSTEM =====
const LANGS = {
  en: {
    // Landing
    tagline: 'Order • Earn Points • Get Rewards',
    myAccount: 'My Account', orderNow: 'Order Now', myStampCard: 'My Stamp Card',
    topUp: 'Top Up', merchant: 'Merchant',
    feat1Title: 'Scan & Order', feat1Desc: 'Scan table QR, order in seconds',
    feat2Title: 'Earn Points', feat2Desc: 'RM1 spent = 1 point earned',
    feat3Title: 'Free Drinks', feat3Desc: 'Redeem for free beverages',
    // Menu
    menu: 'Menu', dineIn: 'Dine In', takeaway: 'Takeaway',
    table: 'Table', change: 'Change',
    selectTable: 'Select Your Table', enterTable: 'Enter your table number to start ordering',
    confirmTable: 'Confirm Table', invalidTable: 'Please enter a valid table number',
    // Menu categories
    catAll: 'All', catNewItems: '✨ New Items',
    catHotDrinks: 'Hot Drinks', catColdDrinks: 'Cold Drinks',
    catFood: 'Food', catDesserts: 'Desserts', catSnacks: 'Snacks',
    // Float cart
    floatViewCart: 'View Cart →',
    floatItem: 'item', floatItems: 'items',
    // Takeaway info bar
    takeawayOrder: 'Takeaway Order', noPickupTime: 'No pickup time set', pickup: 'Pickup',
    // Cart
    yourOrder: 'Your Order', orderType: 'Order Type',
    phoneNumber: 'Phone Number', pickupTime: 'Pickup Time',
    pickupHint: "We'll prepare your order by this time.",
    loyaltyPoints: 'Loyalty Points & Stamp',
    earnHint: 'Enter your phone & tap 🔍 to earn points & stamps',
    phoneLoyalty: 'Phone Number (earn points & stamps)',
    payWallet: 'Pay with Wallet', useWallet: 'Use wallet balance to pay', walletBalance: 'Balance',
    paymentMethod: 'Payment Method',
    cartEmpty: 'Your cart is empty', browseMenu: 'Browse Menu',
    eachUnit: 'each', removeItem: 'Remove',
    orderSummary: 'Order Summary', subtotal: 'Subtotal', sst: 'SST (6%)',
    walletDeduction: 'Wallet Deduction', totalLabel: 'Total',
    pointsEarnLabel: "Points you'll earn",
    specialRequest: 'Special Request', specialRequestPlaceholder: 'e.g. less sugar, no ice...',
    placeOrder: 'Place Order',
    // Order type display in cart
    cartDineIn: 'Dine In', cartTakeaway: 'Takeaway', cartChange: 'Change',
    // Confirm details
    confirmType: 'Type', confirmTable2: 'Table', confirmPhone: 'Phone',
    confirmPickup: 'Pickup Time', confirmItems: 'Items',
    confirmWalletPaid: 'Wallet Paid', confirmTotalPaid: 'Total Paid',
    confirmPayment: 'Payment', confirmPointsEarned: 'Points Earned',
    confirmNote: 'Note', pendingVerification: 'Pending Verification',
    confirmTypeDineIn: '🪑 Dine In', confirmTypeTakeaway: '🛍️ Takeaway',
    // Cash pay confirm
    cashPayCounter: 'Please pay at the counter, then tap the button below.',
    cashPaidBtn: "I've Paid — Notify Kitchen",
    cashPaidDone: 'Payment confirmed! Kitchen is preparing your order.',
    // Toast
    toastTakeaway: '🛍️ Takeaway order placed!', toastDineIn: '🍳 Order sent to kitchen!',
    toastNoPhone: 'Please enter your phone number for Takeaway',
    toastNoTime: 'Please set a pickup time',
    toastNoProof: 'Please upload your payment screenshot first.',
    // Stamp
    enterPhone: 'Enter Your Phone',
    notMember: 'Not a member?', registerHere: 'Register here',
    // Order Confirm
    orderPlaced: 'Order Placed!', thankYou: 'Thank You!',
    orderSent: 'Your order has been sent to the kitchen.',
    orderMore: 'Order More', viewStamp: 'View My Stamp Card', backHome: 'Back to Home',
    // Takeaway modal
    takeawayModalTitle: 'Takeaway Order', takeawayModalSubtitle: 'Enter your pickup details',
    confirmTakeaway: 'Confirm Takeaway', cancelBtn: 'Cancel',
    pickupReadyHint: "We'll have your order ready by this time.",
    // Payment section
    tngScanTitle: 'Scan to Pay via Touch & Go',
    tngAmountLabel: 'Amount', tngUploadHint: 'After payment, upload your screenshot below.',
    uploadScreenshot: 'Upload Payment Screenshot', uploadReceipt: 'Upload Transfer Receipt',
    uploadSizeHint: 'JPG / PNG up to 5MB', bankTitle: 'Bank Transfer Details',
    // Stamp card
    stampReward: 'Reward', stampClaimBtn: 'Claim Reward',
    stampPerPurchase: '1 stamp per purchase',
    stampPerAmount: '1 stamp per RM{v} spent',
    stampPerItem: '1 stamp per {item}',
    stampPerItemGeneric: '1 stamp per qualifying item',
    stampFreeItem: 'Free {item}', stampFreeItemGeneric: 'Free Item',
    stampRmOff: 'RM{v} Off', stampPctOff: '{v}% Off', stampBonusPoints: '+{v} Bonus Points',
    stampsToUnlock: '{n} more stamp to unlock reward', stampsToUnlockPlural: '{n} more stamps to unlock reward',
    stampCollected: 'Collected', stampEmpty: 'Empty',
    stampCompleted: 'Completed {n}×',
    // Customer Auth
    login: 'Login', register: 'Register', fullName: 'Full Name',
    memberDeactivatedMsg: 'Your account has been deactivated. Please contact the merchant.',
    // Dashboard
    memberLabel: 'Member', totalPoints: 'Total Points', memberId: 'Member ID',
    tierProgress: 'Tier Progress',
    tierBronze: 'Bronze\n0', tierSilver: 'Silver\n200', tierGold: 'Gold\n500', tierPlatinum: 'Platinum\n1000',
    redeemRewards: 'Redeem Rewards', viewAllStampCards: 'View All Stamp Cards',
    myOrders: 'My Orders', viewAllOrders: 'View All Orders',
    referralCommissions: 'Referral Commissions', myReferralProgram: 'My Referral Program',
    transactionHistory: 'Transaction History', logout: 'Logout', submitComplaint: 'Submit a Complaint',
    // My Orders page
    loginRequired: 'Login Required', loginToViewOrders: 'Please login to view your order history.',
    goToLogin: 'Go to Login',
    filterAll: 'All', filterPending: 'Pending', filterPreparing: 'Preparing', filterDone: 'Done',
    // Top Up page
    topUpWallet: 'Top Up Wallet', myWallet: 'My Wallet', bonusIncluded: 'bonus included',
    topUpBonusTitle: 'Top Up Bonus!', topUpBonusDesc: 'Top up RM100 and get RM120 credit (FREE RM20 bonus!)',
    selectTopUpAmount: 'Select Top Up Amount', topUpGet: 'Get', noBonus: 'No bonus',
    bestDeal: 'BEST DEAL', free: 'FREE',
    orCustomAmount: 'Or enter custom amount (RM)',
    topUpCustomHint: 'Min RM10. Bonus applies to RM100 and above.',
    youPay: 'You Pay', youGet: 'You Get', bonusLabel: 'Bonus',
    confirmTopUp: 'Confirm Top Up', walletHistory: 'Wallet History',
    // Wallet dashboard
    availableBalance: 'Available Balance', totalToppedUp: 'Total Topped Up', totalBonusEarned: 'Total Bonus Earned',
    // Tier hint
    sinceLabel: 'Since',
    pointsToReach: '{n} more points to reach {tier}!',
    highestTier: '🏆 You reached the highest tier!',
    tierNameSilver: 'Silver', tierNameGold: 'Gold', tierNamePlatinum: 'Platinum',
    // Upload
    screenshotUploaded: 'Screenshot uploaded. Pending merchant verification.',
    screenshotUploaded2: 'Screenshot uploaded', tapToChange: 'Tap to change',
    // Topup submit
    topupSubmitted: '✅ Top up request submitted! Pending merchant approval.',
    // Error toasts
    selectTableFirst: 'Please select a table first!',
    photoUnder5MB: 'Photo must be under 5MB',
    enterValidRate: 'Enter a valid rate (1–100)',
    selectMenuItem: 'Please select a menu item',
    enterPhoneNumber: 'Please enter your phone number',
    memberNotFound: 'Member not found. Please register first.',
    noUnclaimedRewards: 'No unclaimed rewards',
    enterCardName: 'Please enter a card name',
    enterRewardValue: 'Please enter the reward value',
    minimumTopup: 'Minimum top up is RM10',
    selectTopupAmount: 'Please select a top up amount',
    sessionExpired: 'Session expired, please re-enter phone',
    memberNotFoundShort: 'Member not found',
    pleaseLoginFirst: 'Please login first',
    pleaseDescribeIssue: 'Please describe your issue',
    enterPhoneToLogin: 'Please enter phone number',
    memberNotFoundRegister: 'Member not found. Please register.',
    fillNamePhone: 'Please fill in name and phone',
    phoneRegistered: 'Phone already registered!',
    referrerNotFound: 'Referrer not found. Please check the phone number.',
    notEnoughPoints: 'Not enough points!',
    invalidCredentials: 'Invalid credentials!',
    enterPhoneSearch: 'Enter phone number',
    memberNotFoundExcl: 'Member not found!',
    enterValidBill: 'Enter valid bill amount',
    fillNamePrice: 'Fill in name and price',
    qrNotReady: 'QR not ready yet',
    complaintSubmitted: '✅ Complaint submitted! We\'ll get back to you soon.',
    stampCollectedMsg: 'Stamp collected!',
    stampCollectedDetail: 'View your card to claim rewards',
    walletTopupPending: 'Awaiting merchant approval',
    myOrdersEmpty: 'No orders found',
    myOrdersNoOrdersYet: 'No orders yet',
    walletTxnsEmpty: 'No wallet transactions yet',
    topupHistoryEmpty: 'No top up history yet',
    complaintsEmpty: 'No complaints found',
    orderDetailTitle: 'Order Details',
    orderDetailOrderId: 'Order ID',
    orderDetailStatus: 'Status',
    orderDetailType: 'Type',
    orderDetailDate: 'Date',
    orderDetailItems: 'Items Ordered',
    orderDetailSubtotal: 'Subtotal',
    orderDetailTax: 'SST',
    walletTopupLabel: 'Top Up',
    paymentCash: 'Cash',
    paymentTng: 'Touch & Go',
    paymentBank: 'Bank Transfer',
    statusPending: 'Pending',
    statusPreparing: 'Preparing',
    statusDone: 'Done',
    stampRedeemTitle: 'Congratulations!',
    stampRedeemMsg: 'You\'ve collected all stamps!',
    stampRedeemClaim: 'Claim Reward',
    stampRedeemLater: 'Maybe Later',
    newItemsTitle: 'What\'s New at LoyalBrew!',
    newItemsMsg: 'Fresh launches just for you 🎉',
    newItemsOrderNow: 'Order Now',
    newItemsClose: 'Close',
    referralReferral: 'Referral Program',
    referralInviteFriends: 'Invite Friends, Earn Commission!',
    referralShareCode: 'Share your phone number as a referral code. When your friend makes their first order, you earn a commission credited to your wallet!',
    referralCopyCode: 'Copy',
    referralFriendsReferred: 'Friends Referred',
    referralTotalEarned: 'Total Earned',
    referralCommissionRate: 'Commission Rate',
    referralCommissionHistory: 'Commission History',
    referralFriendsYouReferred: 'Friends You Referred',
    referralNoCommissions: 'No commissions yet. Start referring!',
    referralNoFriends: 'No friends referred yet.',
    complaintSubmitComplaint: 'Submit Complaint',
    complaintCategory: 'Complaint Category',
    complaintDescription: 'Description',
    complaintUploadPhoto: 'Upload Photo (optional)',
    complaintTapUpload: 'Tap to upload photo',
    complaintOrderIdOpt: 'Order ID (optional)',
    complaintSubmit: 'Submit Complaint',
    complaintMyComplaints: 'My Complaints',
    complaintComplaintDetail: 'Complaint Detail',
    complaintResponse: 'Response / Action Taken',
    complaintResolve: 'Mark Resolved',
    complaintClose: 'Close',
    complaintNoPhoto: 'Photo attached',
    complaintResolveDone: 'Complaint marked as resolved ✅',
    complaintDetailTitle: 'Complaint Detail',
    complaintEnterResponse: 'Enter your response...',
    newItemsBanner: 'NEW',
    newItemsSpecial: 'Special:',
    newItemsWas: 'was',
    newItemsUntil: 'Until:',
    newItemsNoEnd: 'No end date',
    complaintPhotoAlt: 'Photo',
    awaitingMerchantApproval: 'Awaiting merchant approval',
    newItemsNewTag: 'NEW',
    stampComplete: 'COMPLETE!',
    complaintTab: 'Complaint',
    referralTab: 'Referral',
    orderDetailTotal: 'Total',
    orderDetailPointsEarned: 'Points Earned',
    orderDetailWalletPaid: 'Wallet',
    orderDetailWalletDeductLabel: 'Wallet Deduction',
  },
    stampCollectedDetail: 'View your card to claim rewards',
    walletTopupPending: 'Awaiting merchant approval',
    myOrdersEmpty: 'No orders found',
    myOrdersNoOrdersYet: 'No orders yet',
    walletTxnsEmpty: 'No wallet transactions yet',
    topupHistoryEmpty: 'No top up history yet',
    complaintsEmpty: 'No complaints found',
    orderDetailTitle: 'Order Details',
    orderDetailOrderId: 'Order ID',
    orderDetailStatus: 'Status',
    orderDetailType: 'Type',
    orderDetailDate: 'Date',
    orderDetailItems: 'Items Ordered',
    orderDetailSubtotal: 'Subtotal',
    orderDetailTax: 'SST',
    walletTopupLabel: 'Top Up',
    paymentCash: 'Cash',
    paymentTng: 'Touch & Go',
    paymentBank: 'Bank Transfer',
    statusPending: 'Pending',
    statusPreparing: 'Preparing',
    statusDone: 'Done',
    stampRedeemTitle: 'Congratulations!',
    stampRedeemMsg: 'You\'ve collected all stamps!',
    stampRedeemClaim: 'Claim Reward',
    stampRedeemLater: 'Maybe Later',
    newItemsTitle: 'What\'s New at LoyalBrew!',
    newItemsMsg: 'Fresh launches just for you 🎉',
    newItemsOrderNow: 'Order Now',
    newItemsClose: 'Close',
    referralReferral: 'Referral Program',
    referralInviteFriends: 'Invite Friends, Earn Commission!',
    referralShareCode: 'Share your phone number as a referral code. When your friend makes their first order, you earn a commission credited to your wallet!',
    referralCopyCode: 'Copy',
    referralFriendsReferred: 'Friends Referred',
    referralTotalEarned: 'Total Earned',
    referralCommissionRate: 'Commission Rate',
    referralCommissionHistory: 'Commission History',
    referralFriendsYouReferred: 'Friends You Referred',
    referralNoCommissions: 'No commissions yet. Start referring!',
    referralNoFriends: 'No friends referred yet.',
    complaintSubmitComplaint: 'Submit Complaint',
    complaintCategory: 'Complaint Category',
    complaintDescription: 'Description',
    complaintUploadPhoto: 'Upload Photo (optional)',
    complaintTapUpload: 'Tap to upload photo',
    complaintOrderIdOpt: 'Order ID (optional)',
    complaintSubmit: 'Submit Complaint',
    complaintMyComplaints: 'My Complaints',
    complaintComplaintDetail: 'Complaint Detail',
    complaintResponse: 'Response / Action Taken',
    complaintResolve: 'Mark Resolved',
    complaintClose: 'Close',
    complaintNoPhoto: 'Photo attached',
    complaintResolveDone: 'Complaint marked as resolved ✅',
    complaintDetailTitle: 'Complaint Detail',
    complaintEnterResponse: 'Enter your response...',
    newItemsBanner: 'NEW',
    newItemsSpecial: 'Special:',
    newItemsWas: 'was',
    newItemsUntil: 'Until:',
    newItemsNoEnd: 'No end date',
    complaintPhotoAlt: 'Photo',
    awaitingMerchantApproval: 'Awaiting merchant approval',
    newItemsNewTag: 'NEW',
    stampComplete: 'COMPLETE!',
    complaintTab: 'Complaint',
    referralTab: 'Referral',
    orderDetailTotal: 'Total',
    orderDetailPointsEarned: 'Points Earned',
    orderDetailWalletPaid: 'Wallet',
    orderDetailWalletDeductLabel: 'Wallet Deduction',
  },
  zh: {
    // Landing
    tagline: '点餐 • 赚积分 • 换奖励',
    myAccount: '我的账号', orderNow: '立即点餐', myStampCard: '印章卡',
    topUp: '充值', merchant: '商家',
    feat1Title: '扫码点餐', feat1Desc: '扫桌号二维码，秒速下单',
    feat2Title: '赚取积分', feat2Desc: '消费RM1 = 1积分',
    feat3Title: '免费饮料', feat3Desc: '积分兑换免费饮品',
    // Menu