"""
LoyalBrew i18n 修复脚本 v6 - 修复第一个 LANGS 对象（app 真正用的）
修复目标：第一个 const LANGS = {}（char ~33768，size 25862）
- 添加 zh: {} 块（614个中文字翻译）
- 替换 ms: null 为 ms: {} 块（614个马来文翻译）
"""
import sys, re, shutil
sys.stdout.reconfigure(encoding='utf-8')

SRC = r'C:\Users\Administrator\CodeBuddy\20260416214625\app.js'
BACKUP = r'C:\Users\Administrator\CodeBuddy\20260416214625\app.js.bak6'
shutil.copy2(SRC, BACKUP)
print(f'Backup saved: {BACKUP}')

with open(SRC, 'r', encoding='utf-8') as f:
    content = f.read()

# ── 找到第一个 LANGS 对象 ───────────────────────────────
LANGS_POS = content.index('const LANGS = {')

# 数括号深度，找到第一个 LANGS 的结束位置
depth = 0; i = LANGS_POS + len('const LANGS = {') - 1
while i < len(content):
    if content[i] == '{': depth += 1
    elif content[i] == '}':
        depth -= 1
        if depth == 0:
            LANGS_END = i + 1
            break
    i += 1

first_langs = content[LANGS_POS:LANGS_END]
print(f'First LANGS: char {LANGS_POS} to {LANGS_END}, size={len(first_langs)}')

# ── 提取 EN 块 ──────────────────────────────────────────
en_match = re.search(r'en\s*:\s*\{', first_langs)
en_start = en_match.end()  # 跳过 "en: {"
bdepth = 0; bp = en_start - 1
while bp < len(first_langs):
    c = first_langs[bp]
    if c == '{': bdepth += 1
    elif c == '}':
        if bdepth == 0:
            en_end = bp
            break
        bdepth -= 1
    bp += 1
en_block = first_langs[en_match.start():en_end+1]
pairs = re.findall(r"(\w[\w.]*)\s*:\s*'([^']*)'", en_block)
print(f'EN keys extracted: {len(pairs)}')

# ── 中文翻译 ────────────────────────────────────────────
ZH = {}
for k, v in pairs:
    ZH[k] = v  # 先填充英文作为 fallback

# 覆盖为中文
ZH.update({
  'tagline': '扫码点餐 · 积分换礼 · 轻松赚取',
  'loginLabel': '会员登录',
  'myAccount': '我的账户',
  'orderNow': '立即点餐',
  'myStampCard': '我的印章卡',
  'topUp': '充值',
  'merchant': '商家',
  'feat1Title': '扫码点餐', 'feat1Desc': '扫桌面二维码，几秒完成点餐',
  'feat2Title': '赚取积分', 'feat2Desc': '每消费 RM1 = 获得 1 积分',
  'feat3Title': '免费饮品', 'feat3Desc': '积分兑换免费饮品',
  'menu': '菜单', 'dineIn': '堂食', 'takeaway': '外带',
  'table': '桌位', 'change': '更换',
  'selectTable': '选择您的桌位',
  'enterTable': '输入您的桌号开始点餐',
  'confirmTable': '确认桌位',
  'invalidTable': '请输入有效的桌号',
  'catAll': '全部',
  'catNewItems': '✨ 新品上架',
  'catHotDrinks': '热饮', 'catColdDrinks': '冷饮',
  'catFood': '餐食', 'catDesserts': '甜点', 'catSnacks': '小食',
  'floatViewCart': '查看购物车 →', 'floatItem': '件', 'floatItems': '件',
  'takeawayOrder': '外带订单', 'noPickupTime': '未设置取餐时间', 'pickup': '取餐',
  'yourOrder': '您的订单', 'orderType': '订单类型',
  'phoneNumber': '电话号码', 'pickupTime': '取餐时间',
  'pickupHint': '我们将在此时间备好您的订单',
  'loyaltyPoints': '忠诚积分与印章',
  'earnHint': '输入手机号并点击 🔍 获取积分和印章',
  'phoneLoyalty': '电话号码（获取积分和印章）',
  'payWallet': '用钱包支付', 'useWallet': '使用钱包余额支付',
  'walletBalance': '余额', 'paymentMethod': '支付方式',
  'cartEmpty': '您的购物车是空的', 'browseMenu': '浏览菜单',
  'eachUnit': '每件', 'removeItem': '移除',
  'orderSummary': '订单摘要', 'subtotal': '小计',
  'sst': '消费税 (6%)', 'walletDeduction': '钱包抵扣',
  'totalLabel': '总计', 'pointsEarnLabel': '您将获得积分',
  'specialRequest': '特殊要求',
  'specialRequestPlaceholder': '例如：少糖、去冰...',
  'placeOrder': '提交订单',
  'cartDineIn': '堂食', 'cartTakeaway': '外带', 'cartChange': '更换',
  'confirmType': '类型', 'confirmTable2': '桌位', 'confirmPhone': '电话',
  'confirmPickup': '取餐时间', 'confirmItems': '商品',
  'confirmWalletPaid': '钱包已付', 'confirmTotalPaid': '实付金额',
  'confirmPayment': '支付方式', 'confirmPointsEarned': '获得积分',
  'confirmNote': '备注', 'pendingVerification': '待验证',
  'confirmTypeDineIn': '🪑 堂食', 'confirmTypeTakeaway': '🛍️ 外带',
  'cashPayCounter': '请到柜台付款，然后点击下方按钮',
  'cashPaidBtn': '已付款 — 通知厨房',
  'cashPaidDone': '付款已确认！厨房正在准备您的订单',
  'confirmReceivedBtn': '确认收货 / 完成订单',
  'orderPlaced': '订单已提交！',
  'orderSent': '您的订单已发送至厨房',
  'orderCompletedTitle': '订单完成',
  'orderCompletedMsg': '🎉 订单完成！感谢您的订购',
  'enterPhone': '输入您的手机号',
  'enterPhoneNumber': '请输入手机号',
  'enterPhoneSearch': '输入手机号',
  'enterPhoneToLogin': '请输入手机号登录',
  'phoneRegistered': '该手机号已注册！',
  'fillNamePhone': '请填写姓名和手机号',
  'register': '注册', 'registerHere': '在此注册',
  'notMember': '还不是会员？', 'goToLogin': '前往会员登录',
  'logout': '退出登录', 'welcomeBack': '欢迎回来',
  'login': '登录',
  'invalidCredentials': '凭证无效！',
  'loginRequired': '需要会员登录',
  'sessionExpired': '会话已过期，请重新输入手机号',
  'memberNotFound': '会员未找到，请先注册',
  'memberNotFoundExcl': '会员未找到！',
  'memberNotFoundRegister': '会员未找到，请注册',
  'memberNotFoundShort': '会员未找到',
  'memberDeactivatedMsg': '您的账户已被停用，请联系商家',
  'noStampCardsYet': '还没有印章卡', 'noStampCards': '暂无印章卡',
  'stampComplete': '完成！', 'stampCollected': '已收集',
  'stampCollectedMsg': '印章已收集！',
  'stampCollectedDetail': '查看您的卡以领取奖励',
  'stampEmpty': '空',
  'stampFreeItem': '免费 {item}',
  'stampFreeItemGeneric': '免费商品',
  'stampPerAmount': '消费 RM{v} = 1 印章',
  'stampPerItem': '每件 {item} = 1 印章',
  'stampPerItemGeneric': '每件符合商品 = 1 印章',
  'stampPerPurchase': '每消费一次 = 1 印章',
  'stampClaimBtn': '领取奖励',
  'stampRedeemClaim': '领取奖励',
  'stampRedeemLater': '稍后再说',
  'stampRedeemMsg': '您收集了 {n} 个印章！',
  'stampRedeemTitle': '恭喜！',
  'stampReward': '奖励',
  'stampRmOff': '立减 RM{v}',
  'stampPctOff': '{v}% 折扣',
  'stampBonusPoints': '+{v} 奖励积分',
  'stampsToUnlock': '再集 {n} 个印章即可解锁奖励',
  'stampsToUnlockPlural': '再集 {n} 个印章即可解锁奖励',
  'highestTier': '🏆 您已达到最高等级！',
  'stampCompleted': '已完成 {n}×',
  'viewAllStampCards': '查看全部印章卡',
  'viewStamp': '查看我的印章卡',
  'redeemRewards': '兑换奖励',
  'noUnclaimedRewards': '暂无待领取奖励',
  'everyPurchase1Stamp': '每消费一次 = 1 印章',
  'perRMRule': '每消费 RM1 = 1 印章',
  'perItemRule': '每件指定商品 = 1 印章',
  'freeMenuItem': '免费菜单商品',
  'rmDiscount': '立减金额 (RM)',
  'pctDiscount': '百分比折扣 (%)',
  'bonusPointsReward': '奖励积分',
  'stampCard': '印章卡',
  'redeemReward': '兑换奖励',
  'myOrders': '我的订单',
  'myOrdersEmpty': '暂无订单',
  'myOrdersNoOrdersYet': '暂无订单',
  'loginToViewOrders': '请登录以查看订单历史',
  'viewAllOrders': '查看全部订单',
  'viewOrders2': '查看订单',
  'orderDetailTitle': '订单详情',
  'orderDetailsTitle': '订单详情',
  'orderDetailOrderId': '订单编号',
  'orderDetailDate': '日期',
  'orderDetailType': '类型',
  'orderDetailStatus': '状态',
  'orderDetailItems': '已点商品',
  'orderDetailSubtotal': '小计',
  'orderDetailTax': '消费税',
  'orderDetailTotal': '总计',
  'orderDetailPointsEarned': '获得积分',
  'orderDetailWalletPaid': '钱包支付',
  'orderDetailWalletDeductLabel': '钱包抵扣',
  'filterAll': '全部',
  'filterPending': '待处理',
  'filterPreparing': '制作中',
  'filterDone': '已完成',
  'confirmPoints': '确认积分',
  'orderMore': '加点',
  'statusPending': '待处理',
  'statusPreparing': '制作中',
  'statusDone': '已完成',
  'resolved': '已解决',
  'in_progress': '进行中',
  'myWallet': '我的钱包',
  'walletTopupLabel': '充值',
  'walletTopupPending': '等待商家审批',
  'walletTxnsEmpty': '暂无钱包交易记录',
  'topupHistoryEmpty': '暂无充值记录',
  'topUpWallet': '充值钱包',
  'selectTopUpAmount': '选择充值金额',
  'selectTopupAmount': '请选择充值金额',
  'orCustomAmount': '或输入自定义金额 (RM)',
  'confirmTopUp': '确认充值',
  'topupSubmitted': '✅ 充值请求已提交！等待商家审批',
  'topUpBonusTitle': '充值赠送！',
  'topUpBonusDesc': '充值 RM100 可获 RM120 额度（赠送 RM20！）',
  'topUpCustomHint': '最低 RM10。赠送适用于 RM100 及以上',
  'topUpGateway': '充值（支付网关）',
  'topUpGet': '获取',
  'totalToppedUp': '累计充值',
  'totalPoints': '总积分',
  'availableBalance': '可用余额',
  'totalBonusEarned': '累计获得赠送',
  'pointsToReach': '再积 {n} 分即可达到 {tier}！',
  'noBonus': '无赠送',
  'bonusIncluded': '含赠送',
  'pointsPerRM': '每 RM 积分',
  'youGet': '您获得',
  'youPay': '您支付',
  'will_earn': '将获得',
  'myReferralProgram': '我的推荐计划',
  'referralTab': '推荐',
  'referralReferral': '推荐计划',
  'referralInviteFriends': '邀请好友，赚取佣金！',
  'referralShareCode': '将您的手机号作为推荐码分享。当好友完成首单时，佣金将自动转入您的钱包！',
  'referralSharePrompt': '分享您的手机号 {phone} 作为推荐码，从好友消费中获得 {rate}% 佣金',
  'referralTotalEarned': '累计获得佣金',
  'referralCommissionRate': '佣金比例',
  'referralCurrentRate': '当前比例',
  'referralFriendsReferred': '已推荐好友',
  'referralFriendsYouReferred': '您推荐的好友',
  'referralNoFriends': '暂未推荐好友',
  'referralNoCommissions': '暂无佣金，开始推荐吧！',
  'referralCopyCode': '复制',
  'referralCommissionHistory': '佣金记录',
  'referralCommissionEarned': '已获佣金',
  'referralCommissions': '推荐佣金',
  'referrerNotFound': '推荐人不存在，请检查手机号',
  'enter_your_referrer_s_phone_number_to_link_commissions': '输入推荐人的手机号以关联佣金',
  'credited_to_referrer_s_wallet_after_first_order': '将在好友完成首单后转入推荐人钱包',
  'friendsReferredTitle': '您推荐的好友',
  'friends_referred': '已推荐好友',
  'no_friends_referred_yet': '暂未推荐好友',
  'total_earned': '累计获得',
  'myComplaints': '我的投诉',
  'complaintTab': '投诉',
  'newComplaint': '新的投诉',
  'complaintSubmit': '提交投诉',
  'complaintSubmitComplaint': '提交投诉',
  'complaintDescription': '描述',
  'complaintComplaintDetail': '投诉详情',
  'complaintDetailTitle': '投诉详情',
  'complaintEnterResponse': '输入您的回复...',
  'complaintResponse': '回复 / 已采取行动',
  'complaintResolve': '标记为已解决',
  'complaintResolveDone': '投诉已标记为已解决 ✅',
  'complaintSubmitted': '✅ 投诉已提交！我们会尽快处理',
  'complaintClose': '关闭',
  'complaintTapUpload': '点击上传照片',
  'complaintPhotoAlt': '照片',
  'complaintUploadPhoto': '上传照片（可选）',
  'complaintNoPhoto': '已附照片',
  'complaintsEmpty': '暂无投诉',
  'noComplaintsYet': '暂未提交投诉',
  'complaintCategory': '投诉类别',
  'complaintOrderIdOpt': '订单编号（可选）',
  'pricing_issue': '价格问题',
  'wrong_order': '订单错误',
  'food_quality': '食品质量',
  'service': '服务态度',
  'cleanliness': '卫生问题',
  'waiting_time': '等待时间',
  'other': '其他',
  'shopInfo': '店铺信息',
  'shopSettings2': '店铺设置',
  'saveShop': '保存店铺信息',
  'shopName': '店铺名称',
  'merchantNameDisplay': '商家名称',
  'commission_rate': '佣金比例',
  'pointsSettings': '积分设置',
  'savePoints2': '保存积分设置',
  'enterValidRate': '请输入有效比例（1-100）',
  'enterValidBill': '请输入有效金额',
  'enterRewardValue': '请输入奖励值',
  'enterCardName': '请输入卡名称',
  'qrNotReady': '二维码尚未准备好',
  'noPromos': '暂无优惠',
  'noPromosNow': '暂无可用优惠，稍后再来吧！',
  'promosAndDeals': '优惠与活动',
  'viewAllPromos': '查看全部优惠',
  'allPromos': '全部优惠',
  'bestDeal': '超值优惠',
  'announcement': '公告',
  'noPendingRequests': '暂无待处理请求',
  'refresh': '刷新',
  'quickActions': '快捷操作',
  'view': '查看',
  'back': '返回',
  'backHome': '返回首页',
  'cancelBtn': '取消',
  'new': '新',
  'get': '领取',
  'tapToChange': '点击更换',
  'newItemsTitle': '今日新品 🎉',
  'newItemsMsg': '新品上架啦 🎉',
  'newItemsBanner': '新品',
  'newItemsNewTag': '新品',
  'newItemsSpecial': '特惠：',
  'newItemsWas': '原价',
  'newItemsUntil': '截至：',
  'newItemsNoEnd': '无截止日期',
  'newItemsClose': '关闭',
  'newItemsOrderNow': '立即点餐',
  'noActiveNewItems': '暂无可用新品',
  'noPastLaunches': '暂无历史新品',
  'drinkToday': '今日推荐饮品',
  'welcomeBack': '欢迎回来',
  'thankYou': '谢谢！',
  'free': '免费',
  'enter': '输入',
  'fillNamePrice': '填写名称和价格',
  'sinceLabel': '创建于',
  'fullName': '全名',
  'scan_to_pay': '扫描付款',
  'bankTitle': '银行转账详情',
  'bankAccountDisplay': '银行账户',
  'bankAmountLabel': '金额：RM0.00',
  'paymentBank': '银行转账',
  'paymentCash': '现金',
  'paymentTng': 'Touch & Go',
  'tngScanTitle': '扫描以通过 Touch & Go 付款',
  'tngName': 'Touch & Go',
  'tngAmountLabel': '金额',
  'tngUploadHint': '付款后，请在下方上传截图',
  'uploadScreenshot': '上传付款截图',
  'uploadReceipt': '上传转账凭证',
  'uploadSizeHint': 'JPG / PNG，最大 5MB',
  'photoUploadHint': 'JPG、PNG，最大 5MB',
  'photo_upload_hint': 'JPG、PNG，最大 5MB',
  'tap_to_upload_photo': '点击上传照片',
  'toastNoProof': '请先上传付款截图',
  'photoUnder5MB': '照片大小不能超过 5MB',
  'screenshotUploaded': '截图已上传，等待商家验证',
  'screenshotUploaded2': '截图已上传',
  'selectTableFirst': '请先选择桌号！',
  'selectTopupAmount': '请选择充值金额',
  'minimumTopup': '最低充值金额为 RM10',
  'awaitingMerchantApproval': '等待商家审批',
  'takeawayModalTitle': '外带订单',
  'takeawayModalSubtitle': '输入您的取餐详情',
  'confirmTakeaway': '确认外带',
  'toastDineIn': '🍳 订单已发送至厨房！',
  'toastTakeaway': '🛍️ 外带订单已提交！',
  'toastNoPhone': '请输入手机号（外带）',
  'toastNoTime': '请设置取餐时间',
  'pickupReadyHint': '我们将在此时间备好您的订单。',
  'submitComplaint': '提交投诉',
  'submitComplaintBtn': '提交投诉',
  'pleaseDescribeIssue': '请详细描述您的问题',
  'uploadPhotoOptional': '上传照片（可选）',
  'order_id_optional': '订单编号（可选）',
  'noStampCards': '暂无印章卡',
  'active_new_launches': '进行中的发布',
  'active_stamp_cards': '活跃印章卡',
  'add_bonus_rule': '添加奖励规则',
  'add_points': '添加积分',
  'add_points_manually': '手动加分',
  'add_rule': '添加规则',
  'add_to_menu': '添加到菜单',
  'admin': '管理',
  'all': '全部',
  'all_members': '全部会员',
  'all_orders': '全部订单',
  'announcement_placeholder': '输入公告内容...',
  'announcement_text': '公告文本',
  'bank_transfer': '银行转账',
  'bonus_points': '奖励积分',
  'cancel': '取消',
  'card_color_theme': '卡颜色主题',
  'card_name': '卡名称',
  'card_name_placeholder': '例如：集满10个印章换免费饮料',
  'cash': '现金',
  'category': '分类',
  'click_to_upload_photo': '点击上传图片',
  'close': '关闭',
  'cold_drinks': '冷饮',
  'commission_history': '佣金历史',
  'commission_records': '佣金记录',
  'commission_settings': '佣金设置',
  'commissions': '佣金',
  'complaint_category': '投诉类别',
  'complaint_detail': '投诉详情',
  'complaints': '投诉',
  'confirm_deactivate': '确认停用',
  'create_account': '创建账户',
  'create_stamp_card': '创建印章卡',
  'deactivate_member': '停用会员',
  'description': '描述',
  'desserts': '甜点',
  'done': '已完成',
  'emoji_icon': '表情图标',
  'end_date': '结束日期',
  'expiry_date': '到期日期',
  'food': '食物',
  'free_item': '免费项目',
  'free_menu_item': '免费菜单项目',
  'hot_drinks': '热饮',
  'item_name': '商品名称',
  'item_photo': '商品图片',
  'kitchen': '厨房',
  'launch_date': '发布日期',
  'launch_new_item': '发布新品',
  'login_to_dashboard': '登录后台',
  'members': '会员',
  'menu_items': '菜单项',
  'merchant_login': '商家登录',
  'new_complaint': '新投诉',
  'no_active_new_items': '没有进行中的新项目',
  'no_past_launches': '没有过去的发布',
  'no_pickup_time_set': '未设置取餐时间',
  'no_stamp_cards_yet': '还没有印章卡',
  'optional': '可选',
  'orders': '订单',
  'orders_today': '今日订单',
  'overview': '概览',
  'password': '密码',
  'past_launches': '历史发布',
  'pending': '待处理',
  'phone_number': '电话号码',
  'points': '积分',
  'points_issued': '已发积分',
  'preparing': '准备中',
  'qr_codes': '二维码',
  'recent_transactions': '最近交易',
  'referral_commission_rate': '推荐佣金率',
  'remove_photo': '移除照片',
  'revenue_today': '今日营收',
  'reward_type': '奖励类型',
  'save_password': '保存密码',
  'select_menu_item': '选择菜单项',
  'settings': '设置',
  'snacks': '小吃',
  'stamp_cards': '印章卡',
  'stamp_rule': '印章规则',
  'stamp_rule_placeholder': '例如：每消费RM10得1个印章',
  'stamps_required_to_complete': '完成所需印章数',
  'submit_complaint': '提交投诉',
  'top_up': '充值',
  'username': '用户名',
  'wrong_order': '订单错误',
  'generate_qr_codes': '生成二维码',
  'generate_table_qr_codes': '生成桌位二维码',
  'number_of_tables': '桌位数量',
  'superAdmin': '超级管理员',
  'mPhComplaintDesc': '请详细描述您的问题...',
  'mPhComplaintOrderId': '例如：ORD123456',
  'mLoginBtn': '登录',
  'mLoginHint': '输入您的商家ID和密码',
  'mInvalidCredentials': '凭证无效',
  'mVerify': '验证',
  'mRefreshed': '已刷新',
  'mBalance': '余额',
  'mStampsLabel': '印章',
  'mPoints': '积分',
  'mBonusPtsLabel': '奖励积分',
  'mBonusPercent': '奖励百分比',
  'mBonusPct': '%',
  'mBonusExpiry': '有效期',
  'mMinAmt': '最低金额 (RM)',
  'mEnterValidBill': '输入有效金额',
  'mEnterValidRate': '输入有效比例（1-100）',
  'mEnterPhone': '输入手机号',
  'mEnterCardName': '输入卡名称',
  'mFillNamePrice': '填写名称和价格',
  'mFirstOrderDone': '首单已完成！',
  'mNotOrderedYet': '尚未点单',
  'mFreePrefix': '免费',
  'mFreeItem': '免费商品',
  'mFreeCoffee': '免费咖啡',
  'mRewardFreeItem': '免费商品',
  'mRewardFlatDiscount': '固定折扣 (RM)',
  'mRewardPctDiscount': '百分比折扣 (%)',
  'mRewardBonusPoints': '奖励积分',
  'mPurchase': '消费',
  'mRmOff': 'RM 折扣',
  'mPctOff': '% 折扣',
  'mApprove': '批准',
  'mReject': '拒绝',
  'mNoMembersYet': '暂无会员',
  'mNoMembersFound': '未找到会员',
  'mMemberActive': '活跃',
  'mMemberInactive': '已停用',
  'mActivateMember': '启用会员',
  'mDeactivateMember': '停用会员',
  'mActivateBtn': '启用',
  'mDeactivateBtn': '停用',
  'mConfirmActivate': '确认启用此会员？',
  'mConfirmDeactivate': '确认停用此会员？',
  'mNoOrdersFound': '未找到订单',
  'mNoOrdersCategory': '此分类暂无订单',
  'mOrderPrepare': '准备中',
  'mOrderCompleted': '已完成',
  'mOrderDone': '已完成',
  'mOrderPickup': '待取餐',
  'mOrderTable': '桌位',
  'mOrderTakeaway': '外带',
  'mOrderMovedPreparing': '已移至准备中',
  'mComplaintOpen': '待处理',
  'mComplaintInProgress': '处理中',
  'mComplaintResolved': '已解决',
  'mNoComplaintsFound': '暂无投诉',
  'mNoCommissions': '暂无佣金',
  'mNoPaymentProofs': '暂无付款凭证',
  'mNoPendingRequests': '暂无待处理请求',
  'mPaymentVerified': '已验证',
  'mPaymentRejected': '已拒绝',
  'mTopupApproved': '已批准',
  'mTopupRejected': '已拒绝',
  'mTopupSubmitted': '充值已提交！',
  'mNoTopupHistory': '暂无充值记录',
  'mNoTransactions': '暂无交易',
  'mNoStampCardsYet': '暂无印章卡',
  'mNoActiveItems': '暂无活跃商品',
  'mNoPastLaunches': '暂无历史新品',
  'mQRNotReady': '二维码未准备好',
  'mQRPrint': '打印二维码',
  'mQRTable': '桌位二维码',
  'mSelectMenuItem': '选择菜单商品',
  'mChooseAnItem': '选择一件商品',
  'mExpired': '已过期',
  'mDetailStatus': '状态',
  'mDetailDate': '日期',
  'mDetailCustomer': '顾客',
  'mDetailOrder': '订单',
  'mDetailCategory': '分类',
  'mDetailPrevResponse': '之前的回复',
  'mStampPerPurchase': '每消费一次',
  'mStampPerItem': '每件商品',
  'mStampPerRM': '每 RM',
  'mStampActive': '活跃',
  'mStampPaused': '已暂停',
  'mStampPause': '暂停',
  'mStampActivate': '启用',
  'mStampDelete': '删除',
  'mStampMembers': '会员',
  'mAddRule': '添加规则',
  'mDeleteRule': '删除规则',
  'mNiDeactivate': '停用',
  'mNiDelete': '删除',
  'mNiEnds': '截止：',
  'mNiLaunch': '发布',
  'mNiNoEndDate': '无截止日期',
  'mNiSpecial': '特惠：',
  'mNiWas': '原价',
  'mCatHotDrinks': '热饮',
  'mCatColdDrinks': '冷饮',
  'mCatFood': '餐食',
  'mCatDesserts': '甜点',
  'mCatSnacks': '小食',
  'mCatPromotions': '促销',
  'mPromoPrice': '促销价 (RM)',
  'mPromoPriceLbl': '促销价 (RM)',
  'mPromoPriceDesc': '可选 - 用于非高峰特价',
  'mNoExpiry': '无有效期',
  'mMinTopupAmount': '最低充值金额为 RM10',
  'mKitchenOrderCompleted': '订单已完成',
  'mKitchenCookingStarted': '已开始制作',
  'mKitchenCompleted': '已完成',
  'mKitchenGuest': '顾客',
  'mKitchenMarkDone': '标记完成',
  'mKitchenStartCooking': '开始制作',
  'mKitchenPickup': '取餐',
  'mKitchenTable': '桌位',
  'mKitchenTakeaway': '外带',
  'mComplaintNoPhoto': '无照片',
  'mPhotoUnder5MB': '照片大小不能超过 5MB',
  'menuMgmt2': '菜单管理',
  'kitchenDisplay2': '厨房显示屏',
  'memberId': '会员编号',
  'memberLabel': '会员',
  'searchForAMember': '搜索会员',
  'stampCollectedMsg': '印章已收集！',
  'stampCollectedDetail': '查看印章卡领取奖励',
  'totalPoints': '总积分',
  'notEnoughPoints': '积分不足！',
  'member_stamp_progress': '印章进度',
  'member_wallet_balances': '钱包余额',
  'tierProgress': '等级进度',
  'tierBronze': '青铜\n0',
  'tierSilver': '白银\n200',
  'tierGold': '黄金\n500',
  'tierPlatinum': '铂金\n1000',
  'tierNameSilver': '白银',
  'tierNameGold': '黄金',
  'tierNamePlatinum': '铂金',
  'ads': '广告',
  'ad_title': '广告标题',
  'ad_image': '广告图片',
  'ad_link': '链接网址（可选）',
  'ad_position': '展示位置',
  'ad_priority': '优先级',
  'ad_statistics': '广告统计',
  'create_ad': '创建新广告',
  'all_ads': '全部广告',
  'active_ads': '活跃广告',
  'no_ads_yet': '暂无广告',
  'no_active_ads': '暂无活跃广告',
  'click_to_upload_ad_image': '点击上传广告图片',
  'landing_page_top': '落地页顶部',
  'kitchen_display': '厨房显示屏',
  'higher_shows_first': '数字越大越靠前显示',
  'top_up_history': '充值记录',
  'top_up_bonus_settings': '充值赠送设置',
  'pending_top_up_requests': '待处理充值请求',
  'pending_payment_proofs': '待处理付款凭证',
  'no_pending_payment_proofs': '暂无待处理付款凭证',
  'no_pending_requests': '暂无待处理请求',
  'customer_complaints': '顾客投诉',
  'loyalbrew_lang': 'zh',
  'loyalbrew_merchant_lang': 'zh',
  'loyalbrew_merchant_phone': '',
  'loyalbrew_topup_bonus_rules': '',
  'Item removed': '商品已移除',
  'Points settings saved!': '积分设置已保存！',
  'Shop info saved!': '店铺信息已保存！',
  '加分成功': '积分添加成功！',
  '🎉 Stamp collected! Check your stamp card!': '🎉 印章已收集！查看您的印章卡！',
  '🚀 New item launched!': '🚀 新品上架！',
})

# ── 马来文翻译 ───────────────────────────────────────────
MS = {}
for k, v in pairs:
    MS[k] = v

MS.update({
  'tagline': 'Pesan • Kumpul Mata • Dapatkan Ganjaran',
  'loginLabel': 'Log Masuk Ahli',
  'myAccount': 'Akaun Saya',
  'orderNow': 'Pesan Sekarang',
  'myStampCard': 'Kad Setem Saya',
  'topUp': 'Isi Semula',
  'merchant': 'Peniaga',
  'feat1Title': 'Imbas & Pesan',
  'feat1Desc': 'Imbas QR meja, pesan dalam saat',
  'feat2Title': 'Kumpul Mata',
  'feat2Desc': 'RM1 dibelanja = 1 mata earned',
  'feat3Title': 'Minuman Percuma',
  'feat3Desc': 'Tukar mata untuk minuman percuma',
  'menu': 'Menu',
  'dineIn': 'Makan Di Sini',
  'takeaway': 'Bawa Pulang',
  'table': 'Meja',
  'change': 'Tukar',
  'selectTable': 'Pilih Meja Anda',
  'enterTable': 'Masukkan nombor meja untuk mula memesan',
  'confirmTable': 'Sahkan Meja',
  'invalidTable': 'Sila masukkan nombor meja yang sah',
  'catAll': 'Semua',
  'catNewItems': '✨ Item Baharu',
  'catHotDrinks': 'Minuman Panas',
  'catColdDrinks': 'Minuman Sejuk',
  'catFood': 'Makanan',
  'catDesserts': 'Pencuci Mulut',
  'catSnacks': 'Snek',
  'floatViewCart': 'Lihat Troli →',
  'floatItem': 'item',
  'floatItems': 'item',
  'takeawayOrder': 'Pesanan Bawa Pulang',
  'noPickupTime': 'Masa pengambilan belum ditetapkan',
  'pickup': 'Pengambilan',
  'yourOrder': 'Pesanan Anda',
  'orderType': 'Jenis Pesanan',
  'phoneNumber': 'Nombor Telefon',
  'pickupTime': 'Masa Pengambilan',
  'pickupHint': 'Kami akan sediakan pesanan anda pada masa ini.',
  'loyaltyPoints': 'Mata Kesetiaan & Setem',
  'earnHint': 'Masukkan telefon & tekan 🔍 untuk kumpul mata & setem',
  'phoneLoyalty': 'Nombor Telefon (kumpul mata & setem)',
  'payWallet': 'Bayar dengan Wallet',
  'useWallet': 'Gunakan baki wallet untuk bayar',
  'walletBalance': 'Baki',
  'paymentMethod': 'Kaedah Pembayaran',
  'cartEmpty': 'Troli anda kosong',
  'browseMenu': 'Lihat Menu',
  'eachUnit': 'setiap',
  'removeItem': 'Buang',
  'orderSummary': 'Ringkasan Pesanan',
  'subtotal': 'Subtotal',
  'sst': 'SST (6%)',
  'walletDeduction': 'Tolak Wallet',
  'totalLabel': 'Jumlah',
  'pointsEarnLabel': 'Mata yang anda perolehi',
  'specialRequest': 'Permintaan Khas',
  'specialRequestPlaceholder': 'cth: kurang gula, tanpa ais...',
  'placeOrder': 'Hantar Pesanan',
  'cartDineIn': 'Makan Di Sini',
  'cartTakeaway': 'Bawa Pulang',
  'cartChange': 'Tukar',
  'confirmType': 'Jenis',
  'confirmTable2': 'Meja',
  'confirmPhone': 'Telefon',
  'confirmPickup': 'Masa Pengambilan',
  'confirmItems': 'Item',
  'confirmWalletPaid': 'Wallet Dibayar',
  'confirmTotalPaid': 'Jumlah Dibayar',
  'confirmPayment': 'Pembayaran',
  'confirmPointsEarned': 'Mata Diperolehi',
  'confirmNote': 'Nota',
  'pendingVerification': 'Menunggu Pengesahan',
  'confirmTypeDineIn': '🪑 Makan Di Sini',
  'confirmTypeTakeaway': '🛍️ Bawa Pulang',
  'cashPayCounter': 'Sila bayar di kaunter, kemudian tekan butang di bawah.',
  'cashPaidBtn': 'Saya Sudah Bayar — Beritahu Dapur',
  'cashPaidDone': 'Pembayaran disahkan! Dapur sedang menyediakan pesanan anda.',
  'confirmReceivedBtn': 'Sahkan Terima / Lengkapkan Pesanan',
  'orderPlaced': 'Pesanan Berjaya!',
  'orderSent': 'Pesanan anda telah dihantar ke dapur.',
  'orderCompletedTitle': 'Pesanan Selesai',
  'orderCompletedMsg': '🎉 Pesanan selesai! Terima kasih atas pesanan anda.',
  'enterPhone': 'Masukkan Nombor Telefon Anda',
  'enterPhoneNumber': 'Sila masukkan nombor telefon',
  'enterPhoneSearch': 'Masukkan nombor telefon',
  'enterPhoneToLogin': 'Sila masukkan nombor telefon untuk log masuk',
  'phoneRegistered': 'Nombor telefon telah berdaftar!',
  'fillNamePhone': 'Sila isi nama dan nombor telefon',
  'register': 'Daftar',
  'registerHere': 'Daftar di sini',
  'notMember': 'Bukan ahli?',
  'goToLogin': 'Pergi ke Log Masuk Ahli',
  'logout': 'Log Keluar',
  'welcomeBack': 'Selamat Kembali',
  'login': 'Log Masuk',
  'invalidCredentials': 'Kelayakan tidak sah!',
  'loginRequired': 'Log Masuk Ahli Diperlukan',
  'sessionExpired': 'Sesi tamat, sila masukkan nombor telefon semula',
  'memberNotFound': 'Ahli tidak dijumpai, sila daftar dahulu',
  'memberNotFoundExcl': 'Ahli tidak dijumpai!',
  'memberNotFoundRegister': 'Ahli tidak dijumpai, sila daftar',
  'memberNotFoundShort': 'Ahli tidak dijumpai',
  'memberDeactivatedMsg': 'Akaun anda telah dinyahaktifkan. Sila hubungi peniaga.',
  'noStampCardsYet': 'Belum ada kad setem',
  'noStampCards': 'Tiada kad setem',
  'stampComplete': 'SELESAI!',
  'stampCollected': 'Dikumpul',
  'stampCollectedMsg': 'Setem dikumpul!',
  'stampCollectedDetail': 'Lihat kad anda untuk tuntut ganjaran',
  'stampEmpty': 'Kosong',
  'stampFreeItem': 'Percuma {item}',
  'stampFreeItemGeneric': 'Barang Percuma',
  'stampPerAmount': '1 setem per RM{v} dibelanja',
  'stampPerItem': '1 setem per {item}',
  'stampPerItemGeneric': '1 setem per item berkelayakan',
  'stampPerPurchase': 'Setiap pembelian = 1 setem',
  'stampClaimBtn': 'Tuntut Ganjaran',
  'stampRedeemClaim': 'Tuntut Ganjaran',
  'stampRedeemLater': 'Nanti Sahaja',
  'stampRedeemMsg': 'Anda telah kumpul {n} setem!',
  'stampRedeemTitle': 'Tahniah!',
  'stampReward': 'Ganjaran',
  'stampRmOff': 'RM{v} Off',
  'stampPctOff': '{v}% Off',
  'stampBonusPoints': '+{v} Mata Bonus',
  'stampsToUnlock': '{n} setem lagi untuk buka ganjaran',
  'stampsToUnlockPlural': '{n} setem lagi untuk buka ganjaran',
  'highestTier': '🏆 Anda telah capai rank tertinggi!',
  'stampCompleted': 'Selesai {n}×',
  'viewAllStampCards': 'Lihat Semua Kad Setem',
  'viewStamp': 'Lihat Kad Setem Saya',
  'redeemRewards': 'Tukar Ganjaran',
  'noUnclaimedRewards': 'Tiada ganjaran belum dituntut',
  'everyPurchase1Stamp': 'Setiap pembelian = 1 setem',
  'perRMRule': 'Setiap RM1 = 1 setem',
  'perItemRule': 'Setiap barang tertentu = 1 setem',
  'freeMenuItem': 'Barang Menu Percuma',
  'rmDiscount': 'Potongan RM (RM)',
  'pctDiscount': 'Diskaun Peratus (%)',
  'bonusPointsReward': 'Mata Bonus',
  'stampCard': 'Kad Setem',
  'redeemReward': 'Tukar Ganjaran',
  'myOrders': 'Pesanan Saya',
  'myOrdersEmpty': 'Tiada pesanan',
  'myOrdersNoOrdersYet': 'Belum ada pesanan',
  'loginToViewOrders': 'Sila log masuk untuk lihat sejarah pesanan',
  'viewAllOrders': 'Lihat Semua Pesanan',
  'viewOrders2': 'Lihat Pesanan',
  'orderDetailTitle': 'Butiran Pesanan',
  'orderDetailsTitle': 'Butiran Pesanan',
  'orderDetailOrderId': 'ID Pesanan',
  'orderDetailDate': 'Tarikh',
  'orderDetailType': 'Jenis',
  'orderDetailStatus': 'Status',
  'orderDetailItems': 'Barang Dipesan',
  'orderDetailSubtotal': 'Subtotal',
  'orderDetailTax': 'SST',
  'orderDetailTotal': 'Jumlah',
  'orderDetailPointsEarned': 'Mata Diperolehi',
  'orderDetailWalletPaid': 'Wallet',
  'orderDetailWalletDeductLabel': 'Tolak Wallet',
  'filterAll': 'Semua',
  'filterPending': 'Menunggu',
  'filterPreparing': 'Menyediakan',
  'filterDone': 'Selesai',
  'confirmPoints': 'Sahkan Mata',
  'orderMore': 'Pesan Lagi',
  'statusPending': 'Menunggu',
  'statusPreparing': 'Menyediakan',
  'statusDone': 'Selesai',
  'resolved': 'Diselesaikan',
  'in_progress': 'Dalam Proses',
  'myWallet': 'Wallet Saya',
  'walletTopupLabel': 'Isi Semula',
  'walletTopupPending': 'Menunggu kelulusan peniaga',
  'walletTxnsEmpty': 'Tiada transaksi wallet lagi',
  'topupHistoryEmpty': 'Tiada sejarah isi semula',
  'topUpWallet': 'Isi Semula Wallet',
  'selectTopUpAmount': 'Pilih Jumlah Isi Semula',
  'selectTopupAmount': 'Sila pilih jumlah isi semula',
  'orCustomAmount': 'Atau masukkan jumlah sendiri (RM)',
  'confirmTopUp': 'Sahkan Isi Semula',
  'topupSubmitted': '✅ Permintaan isi semula dihantar! Menunggu kelulusan peniaga',
  'topUpBonusTitle': 'Bonus Isi Semula!',
  'topUpBonusDesc': 'Isi semula RM100 dapat RM120 kredit (BONUS RM20 percuma!)',
  'topUpCustomHint': 'Min RM10. Bonus terpakai untuk RM100 dan ke atas.',
  'topUpGateway': 'Isi Semula (Gateway Pembayaran)',
  'topUpGet': 'Dapat',
  'totalToppedUp': 'Jumlah Diisi Semula',
  'totalPoints': 'Jumlah Mata',
  'availableBalance': 'Baki Tersedia',
  'totalBonusEarned': 'Jumlah Bonus Diperolehi',
  'pointsToReach': '{n} mata lagi untuk capai {tier}!',
  'noBonus': 'Tiada bonus',
  'bonusIncluded': 'bonus termasuk',
  'pointsPerRM': 'Mata per RM',
  'youGet': 'Anda Dapat',
  'youPay': 'Anda Bayar',
  'will_earn': ' akan dapat',
  'myReferralProgram': 'Program Rujukan Saya',
  'referralTab': 'Rujukan',
  'referralReferral': 'Program Rujukan',
  'referralInviteFriends': 'Jemput Kawan, Dapat Komisen!',
  'referralShareCode': 'Kongsikan nombor telefon anda sebagai kod rujukan. Apabila kawan anda buat pesanan pertama, komisen akan masuk ke wallet anda!',
  'referralSharePrompt': 'Kongsikan telefon {phone} sebagai kod rujukan untuk dapat {rate}% dari kawan anda',
  'referralTotalEarned': 'Jumlah Diperolehi',
  'referralCommissionRate': 'Kadar Komisen',
  'referralCurrentRate': 'Kadar Semasa',
  'referralFriendsReferred': 'Kawan Dirujuk',
  'referralFriendsYouReferred': 'Kawan Yang Anda Rujuk',
  'referralNoFriends': 'Belum ada kawan dirujuk',
  'referralNoCommissions': 'Tiada komisen lagi. Mula rujuk sekarang!',
  'referralCopyCode': 'Salin',
  'referralCommissionHistory': 'Sejarah Komisen',
  'referralCommissionEarned': 'Komisen Diperolehi',
  'referralCommissions': 'Komisen Rujukan',
  'referrerNotFound': 'Perujuk tidak dijumpai. Sila semak nombor telefon.',
  'enter_your_referrer_s_phone_number_to_link_commissions': 'Masukkan nombor telefon perujuk untuk link komisen',
  'credited_to_referrer_s_wallet_after_first_order': 'Akan dikredit ke wallet perujuk selepas pesanan pertama',
  'friendsReferredTitle': 'Kawan Yang Anda Rujuk',
  'friends_referred': 'Kawan Dirujuk',
  'no_friends_referred_yet': 'Belum ada kawan dirujuk',
  'total_earned': 'Jumlah Diperolehi',
  'myComplaints': 'Aduan Saya',
  'complaintTab': 'Aduan',
  'newComplaint': 'Aduan Baharu',
  'complaintSubmit': 'Hantar Aduan',
  'complaintSubmitComplaint': 'Hantar Aduan',
  'complaintDescription': 'Penerangan',
  'complaintComplaintDetail': 'Butiran Aduan',
  'complaintDetailTitle': 'Butiran Aduan',
  'complaintEnterResponse': 'Masukkan jawapan anda...',
  'complaintResponse': 'Jawapan / Tindakan Diambil',
  'complaintResolve': 'Tanda Selesai',
  'complaintResolveDone': 'Aduan ditanda selesai ✅',
  'complaintSubmitted': '✅ Aduan dihantar! Kami akan proses secepat mungkin',
  'complaintClose': 'Tutup',
  'complaintTapUpload': 'Tekan untuk muat naik foto',
  'complaintPhotoAlt': 'Foto',
  'complaintUploadPhoto': 'Muat Naik Foto (opsyenal)',
  'complaintNoPhoto': 'Foto dilampirkan',
  'complaintsEmpty': 'Tiada aduan',
  'noComplaintsYet': 'Belum ada aduan dihantar',
  'complaintCategory': 'Kategori Aduan',
  'complaintOrderIdOpt': 'ID Pesanan (opsyenal)',
  'pricing_issue': 'Isu Harga',
  'wrong_order': 'Pesanan Salah',
  'food_quality': 'Kualiti Makanan',
  'service': 'Perkhidmatan',
  'cleanliness': 'Kebersihan',
  'waiting_time': 'Masa Menunggu',
  'other': 'Lain-lain',
  'shopInfo': 'Maklumat Kedai',
  'shopSettings2': 'Tetapan Kedai',
  'saveShop': 'Simpan Maklumat Kedai',
  'shopName': 'Nama Kedai',
  'merchantNameDisplay': 'Nama Peniaga',
  'commission_rate': 'Kadar Komisen',
  'pointsSettings': 'Tetapan Mata',
  'savePoints2': 'Simpan Tetapan Mata',
  'enterValidRate': 'Sila masukkan kadar sah (1-100)',
  'enterValidBill': 'Sila masukkan jumlah sah',
  'enterRewardValue': 'Sila masukkan nilai ganjaran',
  'enterCardName': 'Sila masukkan nama kad',
  'qrNotReady': 'QR belum sedia',
  'noPromos': 'Tiada promosi',
  'noPromosNow': 'Tiada promosi tersedia sekarang. Nanti lagi!',
  'promosAndDeals': 'Promosi & Tawaran',
  'viewAllPromos': 'Lihat Semua Promosi',
  'allPromos': 'Semua Promosi',
  'bestDeal': 'TAWARAN TERBAIK',
  'announcement': 'Pengumuman',
  'noPendingRequests': 'Tiada permintaan tertangguh',
  'refresh': 'Muat Semula',
  'quickActions': 'Tindakan Pantas',
  'view': 'Lihat',
  'back': 'Kembali',
  'backHome': 'Kembali ke Laman Utama',
  'cancelBtn': 'Batal',
  'new': 'Baharu',
  'get': 'Dapat',
  'tapToChange': 'Tekan untuk tukar',
  'newItemsTitle': 'Barang Baharu Hari Ini 🎉',
  'newItemsMsg': 'Barang baharu dilancarkan 🎉',
  'newItemsBanner': 'BAHARU',
  'newItemsNewTag': 'BAHARU',
  'newItemsSpecial': 'Istimewa:',
  'newItemsWas': ' sebelum',
  'newItemsUntil': ' sehingga:',
  'newItemsNoEnd': 'Tiada tarikh akhir',
  'newItemsClose': 'Tutup',
  'newItemsOrderNow': 'Pesan Sekarang',
  'noActiveNewItems': 'Tiada barang baharu aktif',
  'noPastLaunches': 'Tiada pelancaran lepas',
  'drinkToday': 'Minuman Hari Ini',
  'thankYou': 'Terima Kasih!',
  'free': 'PERCUMA',
  'enter': 'Masukkan',
  'fillNamePrice': 'Isi nama dan harga',
  'sinceLabel': 'Sejak',
  'fullName': 'Nama Penuh',
  'scan_to_pay': 'Imbas untuk bayar',
  'bankTitle': 'Butiran Transfer Bank',
  'bankAccountDisplay': 'Akaun Bank',
  'bankAmountLabel': 'Jumlah: RM0.00',
  'paymentBank': 'Transfer Bank',
  'paymentCash': 'Tunai',
  'paymentTng': 'Touch & Go',
  'tngScanTitle': 'Imbas untuk Bayar melalui Touch & Go',
  'tngName': 'Touch & Go',
  'tngAmountLabel': 'Jumlah',
  'tngUploadHint': 'Selepas bayaran, muat naik tangkapan skrin di bawah.',
  'uploadScreenshot': 'Muat Naik Screenshot Pembayaran',
  'uploadReceipt': 'Muat Naik Resit Transfer',
  'uploadSizeHint': 'JPG / PNG, maksimum 5MB',
  'photoUploadHint': 'JPG, PNG, maksimum 5MB',
  'photo_upload_hint': 'JPG, PNG, maksimum 5MB',
  'tap_to_upload_photo': 'Tekan untuk muat naik foto',
  'toastNoProof': 'Sila muat naik screenshot pembayaran dulu.',
  'photoUnder5MB': 'Foto mestilah di bawah 5MB',
  'screenshotUploaded': 'Screenshot dimuat naik. Menunggu pengesahan peniaga.',
  'screenshotUploaded2': 'Screenshot dimuat naik',
  'selectTableFirst': 'Sila pilih meja dahulu!',
  'minimumTopup': 'Isi semula minimum adalah RM10',
  'awaitingMerchantApproval': 'Menunggu kelulusan peniaga',
  'takeawayModalTitle': 'Pesanan Bawa Pulang',
  'takeawayModalSubtitle': 'Masukkan butiran pengambilan anda',
  'confirmTakeaway': 'Sahkan Bawa Pulang',
  'toastDineIn': '🍳 Pesanan dihantar ke dapur!',
  'toastTakeaway': '🛍️ Pesanan bawa pulang dihantar!',
  'toastNoPhone': 'Sila masukkan nombor telefon untuk Bawa Pulang',
  'toastNoTime': 'Sila tetapkan masa pengambilan',
  'pickupReadyHint': 'Kami akan sediakan pesanan anda pada masa ini.',
  'submitComplaint': 'Hantar Aduan',
  'submitComplaintBtn': 'Hantar Aduan',
  'pleaseDescribeIssue': 'Sila jelaskan masalah anda dengan terperinci',
  'uploadPhotoOptional': 'Muat Naik Foto (opsyenal)',
  'order_id_optional': 'ID Pesanan (opsyenal)',
  'generate_qr_codes': 'Jana Kod QR',
  'generate_table_qr_codes': 'Jana Kod QR Meja',
  'number_of_tables': 'Bilangan Meja',
  'superAdmin': 'Super Admin',
  'mPhComplaintDesc': 'Sila jelaskan masalah anda dengan terperinci...',
  'mPhComplaintOrderId': 'cth. ORD123456',
  'mLoginBtn': 'Log Masuk',
  'mLoginHint': 'Masukkan Merchant ID dan kata laluan anda',
  'mInvalidCredentials': 'Kelayakan tidak sah',
  'mVerify': 'Sahkan',
  'mRefreshed': 'Dimuat semula',
  'mBalance': 'Baki',
  'mStampsLabel': 'Setem',
  'mPoints': 'Mata',
  'mBonusPtsLabel': 'Mata Bonus',
  'mBonusPercent': 'Peratus Bonus',
  'mBonusPct': '%',
  'mBonusExpiry': 'Tamat Tempoh',
  'mMinAmt': 'Jumlah Min (RM)',
  'mEnterValidBill': 'Masukkan jumlah sah',
  'mEnterValidRate': 'Masukkan kadar sah (1-100)',
  'mEnterPhone': 'Masukkan nombor telefon',
  'mEnterCardName': 'Masukkan nama kad',
  'mFillNamePrice': 'Isi nama dan harga',
  'mFirstOrderDone': 'Pesanan pertama selesai!',
  'mNotOrderedYet': 'Belum lagi pesan',
  'mFreePrefix': 'PERCUMA',
  'mFreeItem': 'Barang Percuma',
  'mFreeCoffee': 'Kopi Percuma',
  'mRewardFreeItem': 'Barang Percuma',
  'mRewardFlatDiscount': 'Diskaun Flat (RM)',
  'mRewardPctDiscount': 'Diskaun Peratus (%)',
  'mRewardBonusPoints': 'Mata Bonus',
  'mPurchase': 'Pembelian',
  'mRmOff': 'RM Off',
  'mPctOff': '% Off',
  'mApprove': 'Lulus',
  'mReject': 'Tolak',
  'mNoMembersYet': 'Belum ada ahli',
  'mNoMembersFound': 'Tiada ahli dijumpai',
  'mMemberActive': 'Aktif',
  'mMemberInactive': 'Tidak Aktif',
  'mActivateMember': 'Aktifkan Ahli',
  'mDeactivateMember': 'Nyahaktifkan Ahli',
  'mActivateBtn': 'Aktifkan',
  'mDeactivateBtn': 'Nyahaktifkan',
  'mConfirmActivate': 'Sahkan aktifkan ahli ini?',
  'mConfirmDeactivate': 'Sahkan nyahaktifkan ahli ini?',
  'mNoOrdersFound': 'Tiada pesanan dijumpai',
  'mNoOrdersCategory': 'Tiada pesanan dalam kategori ini.',
  'mOrderPrepare': 'Menyediakan',
  'mOrderCompleted': 'Selesai',
  'mOrderDone': 'Selesai',
  'mOrderPickup': 'Pengambilan',
  'mOrderTable': 'Meja',
  'mOrderTakeaway': 'Bawa Pulang',
  'mOrderMovedPreparing': 'Dipindahkan ke Menyediakan',
  'mComplaintOpen': 'Buka',
  'mComplaintInProgress': 'Dalam Proses',
  'mComplaintResolved': 'Diselesaikan',
  'mNoComplaintsFound': 'Tiada aduan dijumpai.',
  'mNoCommissions': 'Tiada komisen dijumpai.',
  'mNoPaymentProofs': 'Tiada bukti pembayaran.',
  'mNoPendingRequests': 'Tiada permintaan tertangguh.',
  'mPaymentVerified': 'Disahkan',
  'mPaymentRejected': 'Ditolak',
  'mTopupApproved': 'Diluluskan',
  'mTopupRejected': 'Ditolak',
  'mTopupSubmitted': 'Isi semula dihantar!',
  'mNoTopupHistory': 'Tiada sejarah isi semula.',
  'mNoTransactions': 'Tiada transaksi.',
  'mNoStampCardsYet': 'Belum ada kad setem.',
  'mNoActiveItems': 'Tiada barang aktif.',
  'mNoPastLaunches': 'Tiada pelancaran lepas.',
  'mQRNotReady': 'QR belum sedia',
  'mQRPrint': 'Cetak QR',
  'mQRTable': 'Kod QR Meja',
  'mSelectMenuItem': 'Pilih item menu',
  'mChooseAnItem': 'Pilih satu item',
  'mExpired': 'Tamat Tempoh',
  'mDetailStatus': 'Status',
  'mDetailDate': 'Tarikh',
  'mDetailCustomer': 'Pelanggan',
  'mDetailOrder': 'Pesanan',
  'mDetailCategory': 'Kategori',
  'mDetailPrevResponse': 'Jawapan Sebelum',
  'mStampPerPurchase': 'Per Pembelian',
  'mStampPerItem': 'Per Item',
  'mStampPerRM': 'Per RM',
  'mStampActive': 'Aktif',
  'mStampPaused': 'Ditangguhkan',
  'mStampPause': 'Tangguhkan',
  'mStampActivate': 'Aktifkan',
  'mStampDelete': 'Padam',
  'mStampMembers': 'Ahli',
  'mAddRule': 'Tambah Peraturan',
  'mDeleteRule': 'Padam Peraturan',
  'mNiDeactivate': 'Nyahaktifkan',
  'mNiDelete': 'Padam',
  'mNiEnds': 'Berakhir:',
  'mNiLaunch': 'Lancarkan',
  'mNiNoEndDate': 'Tiada tarikh akhir',
  'mNiSpecial': 'Istimewa:',
  'mNiWas': ' sebelum',
  'mCatHotDrinks': 'Minuman Panas',
  'mCatColdDrinks': 'Minuman Sejuk',
  'mCatFood': 'Makanan',
  'mCatDesserts': 'Pencuci Mulut',
  'mCatSnacks': 'Snek',
  'mCatPromotions': 'Promosi',
  'mPromoPrice': 'Harga Promo (RM)',
  'mPromoPriceLbl': 'Harga Promo (RM)',
  'mPromoPriceDesc': 'opsyenal — untuk istimewa bukan puncak',
  'mNoExpiry': 'Tiada tamat tempoh',
  'mMinTopupAmount': 'Jumlah isi semula minimum adalah RM10',
  'mKitchenOrderCompleted': 'Pesanan Selesai',
  'mKitchenCookingStarted': 'Memulakan Masakan',
  'mKitchenCompleted': 'Selesai',
  'mKitchenGuest': 'Tamu',
  'mKitchenMarkDone': 'Tanda Selesai',
  'mKitchenStartCooking': 'Mula Masak',
  'mKitchenPickup': 'Pengambilan',
  'mKitchenTable': 'Meja',
  'mKitchenTakeaway': 'Bawa Pulang',
  'mComplaintNoPhoto': 'Tiada foto',
  'mPhotoUnder5MB': 'Foto mestilah di bawah 5MB',
  'menuMgmt2': 'Pengurusan Menu',
  'kitchenDisplay2': 'Paparan Dapur',
  'memberId': 'ID Ahli',
  'memberLabel': 'Ahli',
  'searchForAMember': 'Cari Ahli',
  'stampCollectedMsg': 'Setem dikumpul!',
  'stampCollectedDetail': 'Lihat kad untuk tuntut ganjaran',
  'totalPoints': 'Jumlah Mata',
  'notEnoughPoints': 'Mata tidak cukup!',
  'member_stamp_progress': 'Kemajuan Setem',
  'member_wallet_balances': 'Baki Wallet',
  'tierProgress': 'Kemajuan Tahap',
  'tierBronze': 'Gangsa\n0',
  'tierSilver': 'Perak\n200',
  'tierGold': 'Emas\n500',
  'tierPlatinum': 'Platinum\n1000',
  'tierNameSilver': 'Perak',
  'tierNameGold': 'Emas',
  'tierNamePlatinum': 'Platinum',
  'ads': 'Iklan',
  'ad_title': 'Tajuk Iklan',
  'ad_image': 'Imej Iklan',
  'ad_link': 'URL Pautan (opsyenal)',
  'ad_position': 'Kedudukan Paparan',
  'ad_priority': 'Keutamaan',
  'ad_statistics': 'Statistik Iklan',
  'create_ad': 'Buat Iklan Baharu',
  'all_ads': 'Semua Iklan',
  'active_ads': 'Iklan Aktif',
  'no_ads_yet': 'Belum ada iklan',
  'no_active_ads': 'Tiada iklan aktif',
  'click_to_upload_ad_image': 'Klik untuk muat naik imej iklan',
  'landing_page_top': 'Atas Halaman Landasan',
  'kitchen_display': 'Paparan Dapur',
  'higher_shows_first': 'Nombor lebih tinggi = dipapar dulu',
  'top_up_history': 'Sejarah Isi Semula',
  'top_up_bonus_settings': 'Tetapan Bonus Isi Semula',
  'pending_top_up_requests': 'Permintaan Isi Semula Tertangguh',
  'pending_payment_proofs': 'Bukti Pembayaran Tertangguh',
  'no_pending_payment_proofs': 'Tiada bukti pembayaran tertangguh',
  'no_pending_requests': 'Tiada permintaan tertangguh',
  'customer_complaints': 'Aduan Pelanggan',
  'loyalbrew_lang': 'ms',
  'loyalbrew_merchant_lang': 'ms',
  'loyalbrew_merchant_phone': '',
  'loyalbrew_topup_bonus_rules': '',
  'Item removed': 'Barang dibuang',
  'Points settings saved!': 'Tetapan mata disimpan!',
  'Shop info saved!': 'Maklumat kedai disimpan!',
  '加分成功': 'Mata ditambah berjaya!',
  '🎉 Stamp collected! Check your stamp card!': '🎉 Setem dikumpul! Semak kad setem anda!',
  '🚀 New item launched!': '🚀 Barang baharu dilancarkan!',
})

# ── 构建 zh 和 ms 块 ─────────────────────────────────────
def build_block(trans_dict):
    lines = []
    for k, en_val in pairs:
        val = trans_dict.get(k, en_val)
        val = val.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"    {k}: '{val}'")
    return "  },\n  zh: {\n" + ',\n'.join(lines) + ",\n  },\n  ms: {\n"

# 在第一个 LANGS 里：找到 ms: null 的位置
# ms: null 在 first_langs 里的位置
ms_null_pos_in_langs = first_langs.index('ms: null')
ms_null_global_pos = LANGS_POS + ms_null_pos_in_langs
print(f'ms: null global position: {ms_null_global_pos}')

# ZH+MS 新块（不含 ms: null，用新块替代）
new_zh = []
for k, en_val in pairs:
    val = ZH.get(k, en_val)
    val = val.replace("\\", "\\\\").replace("'", "\\'")
    new_zh.append(f"    {k}: '{val}'")

new_ms = []
for k, en_val in pairs:
    val = MS.get(k, en_val)
    val = val.replace("\\", "\\\\").replace("'", "\\'")
    new_ms.append(f"    {k}: '{val}'")

new_lang_blocks = "  zh: {\n" + ',\n'.join(new_zh) + ",\n  },\n  ms: {\n" + ',\n'.join(new_ms) + ",\n  }"

# 替换 ms: null
new_content = content[:ms_null_global_pos] + new_lang_blocks + content[ms_null_global_pos + len('ms: null,'):]

print(f'Original size: {len(content)} chars')
print(f'New size: {len(new_content)} chars')

with open(SRC, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'\nSaved app.js! New size: {len(new_content)}')
print(f'ZH keys: {len(new_zh)}, MS keys: {len(new_ms)}')
print('DONE!')
